### ISSUE TITLE
Configure Search Engine

### ISSUE THREAD

**Issue by spottedmahn** [mrlacey/ErrorHelper#1]
How about making the search engine configurable?  Or just change the default to Google 😜

Awesome tool btw, thanks for creating!

**Comment by mrlacey** [comment]
Does adding a second search option seem like a suitable compromise?

This would give  `Search with Bing` and `Search with Google` options.

**Comment by mrlacey** [comment]
Version 1.1 is now available and it adds the ability to choose either Bing or Google as the search engine it uses.

Go to **Tools > Options > Error Helper** and select your preferred option.

![image](https://user-images.githubusercontent.com/189547/67716828-68e11b00-f9c4-11e9-9496-e764e9768372.png)
If this new functionality is helpful to you I'd appreciate if you leave a review at https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.ErrorHelper&ssr=false#review-details

**Comment by spottedmahn** [comment]
nice 🎉, thanks @mrlacey 👍
