### ISSUE TITLE
Overlapping Error Messages

### ISSUE THREAD

**Issue by arashberlin** [mrlacey/ErrorHelper#11]
How is it possible to change the display hints from your extension?  When I enable your extension there are 2 messages overlapping each other. 

![image](https://user-images.githubusercontent.com/12381397/203039872-e3ca71c9-33fe-4885-aab4-39feec1dea42.png)

Many thanks
Arash

**Comment by arashberlin** [comment]
I answer my question :)

Change Tools >Options > Text Editor >c# >Advanced >Display diagnostics to "on the right edge...". 

![image](https://user-images.githubusercontent.com/12381397/203041454-7069fcd1-5f74-47bc-ac6d-a67519399a38.png)


![image](https://user-images.githubusercontent.com/12381397/203041499-b586aa35-1566-406f-acb8-997329d26220.png)

**Comment by mrlacey** [comment]
The messages this refers to aren't from this extension.
This extension only adds context menu options when you right-click on entries in the ErrorList window. eg:


![image](https://user-images.githubusercontent.com/189547/203067823-c10f4a36-a69d-4abc-a119-39beef79a9ec.png)
