### ISSUE TITLE
strip paths from error messages

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/ErrorHelper#2]
> Does it strip file names/paths out of the error messages too? 

commented at https://developercommunity.visualstudio.com/idea/462457/copy-error-code-and-description-only-from-error-li.html?childToView=793184#comment-793184

**Comment by michael-hawker** [comment]
I find it generally adds extra noise to the search or exposes directory path info I don't want to share.

**Comment by mrlacey** [comment]
Version 1.1 is now available and it adds the ability to remove paths from the value passed to the search engine.

Go to **Tools > Options > Error Helper** to enable this functionality.

![image](https://user-images.githubusercontent.com/189547/67716828-68e11b00-f9c4-11e9-9496-e764e9768372.png)
If this new functionality is helpful to you I'd appreciate if you leave a review at https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.ErrorHelper&ssr=false#review-details
